name: Simple CI  # 工作流的名字

# 触发条件：当 main 分支有 push 或 pull request 时触发
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-code:
    runs-on: ubuntu-latest  # 在 Ubuntu 虚拟机上运行
    steps:
      - uses: actions/checkout@v4 # 步骤1：把代码拉下来

      - name: Set up Python
        uses: actions/setup-python@v4 # 步骤2：安装 Python
        with:
          python-version: "3.10"

      - name: Run Script
        run: python main.py # 步骤3：尝试运行我们的代码
